CREATE SCHEMA IF NOT EXISTS OLIMP  DEFAULT CHARACTER SET utf8;

USE OLIMP;


CREATE TABLE PAIS(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (20),
POPULACAO DECIMAL (15,2),
AREA DECIMAL (15,2),
PRIMARY KEY (ID)
);


CREATE TABLE ANO (
ANO INT NOT NULL ,
TIPO CHAR(1),
PRIMARY KEY (ANO));

CREATE TABLE MODALIDADE(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (20),
OURO INT,
PRATA INT,
BRONZE INT,
PRIMARY KEY (ID));

DROP TABLE MODALIDADE;

CREATE TABLE OLIMPIADA (
TIPO CHAR (1),
ANO INT NOT NULL,
ID_PAIS INT NOT NULL,
ID_MODALIDADE INT NOT NULL,
PRIMARY KEY (ANO, ID_PAIS, ID_MODALIDADE));

ALTER TABLE OLIMPIADA
ADD FOREIGN KEY (ANO) REFERENCES ANO(ANO),
ADD FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID),
ADD FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADE(ID);



INSERT INTO MODALIDADE (NOME,OURO, PRATA, BRONZE) VALUES('BOXE',8,6,3);
INSERT INTO MODALIDADE (NOME,OURO, PRATA, BRONZE) VALUES('CICLISMO',9,6,5);
INSERT INTO MODALIDADE (NOME,OURO, PRATA, BRONZE) VALUES('FUTEBOL',10,5,3);
INSERT INTO MODALIDADE (NOME,OURO, PRATA, BRONZE) VALUES('JUDÔ',7,3,1);
INSERT INTO MODALIDADE (NOME,OURO, PRATA, BRONZE) VALUES('NATAÇÃO',10,9,8);


INSERT INTO PAIS (NOME, POPULACAO, AREA) VALUES ('BRASIL','2343245466','354656.99');
INSERT INTO PAIS (NOME, POPULACAO, AREA) VALUES ('EQUADOR', '5475475472','94343.99');
INSERT INTO PAIS (NOME, POPULACAO, AREA) VALUES ('PERU', '976657657','436565.99');
INSERT INTO PAIS (NOME, POPULACAO, AREA) VALUES ('ISRAEL', '3466547657','54676.99');
INSERT INTO PAIS (NOME, POPULACAO, AREA) VALUES ('ALEMANHA', '43545565657','5465667.99');


INSERT INTO ANO (ANO,TIPO) VALUES (2002,'I');
INSERT INTO ANO (ANO,TIPO) VALUES (2018,'I');
INSERT INTO ANO (ANO,TIPO) VALUES (2006,'I');
INSERT INTO ANO (ANO,TIPO) VALUES (2000,'V');
INSERT INTO ANO (ANO,TIPO) VALUES (2004,'V');

SELECT * FROM ANO;

INSERT INTO OLIMPIADA (TIPO, ANO, ID_PAIS, ID_MODALIDADE) VALUES
('I',1998,1,5),
('I',2002,3,3),
('I',2006,2,2),
('V',2004,4,1),
('V',2000,5,4);





